apiVersion: v1
kind: Pod
metadata:
  name: {{ include "aerial-ru-emulator.fullname" . }}

{{- with .Values.extraSpec }}
spec:
  {{- toYaml . | nindent 2 }}
  {{- end }}

  {{- with .Values.securityContext }}
  securityContext:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  hostNetwork: true

  containers:
  - name: aerial-ctr
    image: {{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}
    imagePullPolicy: Always
    workingDir: {{ .Values.workingDir }}
    command: ["/bin/sh","-c"]
    args: 
    - | 
      sudo ldconfig;
      echo -1 | sudo tee /proc/sys/kernel/sched_rt_runtime_us;
      # sudo cp /opt/nvidia/cuBB/cuPHY-CP/ru-emulator/config/config.yaml /opt/nvidia/cuBB/cuPHY-CP/ru-emulator/config/config_dyn.yaml
      # sed -i.bak 's/    - peerethaddr: .*/    - peerethaddr: "9c:63:c0:d8:eb:9a"/' /opt/nvidia/cuBB/cuPHY-CP/ru-emulator/config/config_dyn.yaml
      # sed -i.bak "s/nic_interface.*/nic_interface: 0000:99:00.0/" /opt/nvidia/cuBB/cuPHY-CP/ru-emulator/config/config_dyn.yaml
      # {{- if .Values.extraSetup }}
      # {{ .Values.extraSetup }}
      # {{- end }}
      # {{- if .Values.overrideRun }}
      # {{ .Values.overrideRun }}
      # {{- else }}
      sudo -E /opt/nvidia/cuBB/build/cuPHY-CP/ru-emulator/ru_emulator/ru_emulator --config config_dyn.yaml {{ .Values.launchPattern }}
      {{- end }}

    securityContext:
      privileged: true
    volumeMounts:
    # - mountPath: /opt/nvidia/cuBB/cuPHY-CP/ru-emulator/config/config_dyn.yaml
    #   name: config
    - mountPath: /hugepages
      name: hugepage
    - mountPath: /dev/shm
      name: dshm
    - mountPath: /lib/modules/
      name: lib-modules
    - mountPath: /usr/src/
      name: host-drivers
    - mountPath: /opt/nvidia/cuBB/testVectors
      name: test-vector
    - mountPath: /opt/nvidia/cuBB/cuPHY-CP/ru-emulator/config/config_dyn.yaml
      name: aerial-ru-emulator-config
      subPath: config.yaml
    {{- with .Values.extraMountPaths }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    resources:
      limits:
        hugepages-1Gi: 4Gi
        memory: 32Gi
        cpu: {{ .Values.cpu }}

  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
  - name: dshm
    # Unable to configure shm size in K8, need to use this WAR: https://github.com/kubernetes/kubernetes/issues/28272#issuecomment-540943623
    emptyDir: {
        medium: 'Memory',
        sizeLimit: '4Gi'
    }
  - name: lib-modules
    hostPath:
      path: /lib/modules/
  - name: host-drivers
    hostPath:
      path: /usr/src/
  - name: config
    hostPath:
      path: /root/workspace/config.yaml
  - name: test-vector
    persistentVolumeClaim:
      claimName: local-pvc-sys-25-2
  - name: aerial-ru-emulator-config
    configMap:
      name: {{ .Chart.Name }}-configmap
  {{- with .Values.extraVolumes }}
  {{- toYaml . | nindent 2 }}
  {{- end }}

  restartPolicy: Never

